---
title: "Population analysis, with COB data, Jan 23rd 2024"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(zoo)
library(readxl)
library(knitr)
library(sf)
library(sp)
library(kableExtra)
library(magick)
library(plotly)    
library(RColorBrewer)
library(htmltools)
library(prettydoc)
library(rmdformats)
library(ggrepel)
library(dplyr)
library(gglaplot)
library(ggplot2)
library(data.table)
library(lubridate)
library(tidyr)
library(scales)
library(ggrepel)
library(stringr)
library(tidyverse)
library(plotly)


#devtools::load_all("C:/demogtools/")

data_dir <- 'DATA/'
chart_dir <- 'C:/Families/Charts/'

#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup_2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Read in population data 

input_totalBirths <- fread(paste0(data_dir,"Fig4_BirthsChange_ed.csv"))%>% 
  data.frame()
input_Births_MothersUKnonUK <- fread(paste0(data_dir,"Fig5_BirthsChange_MothersUKnonUK.csv"))%>% 
  data.frame()
input_Births_MothersRegion <- fread(paste0(data_dir,"Fig6_BirthsChange_nonUK_MothersRegionOB.csv"))%>% 
  data.frame()
```


```{r fig4, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal1 <- gla_pal(palette_type = "categorical",
                  palette_name = "core", n = 3)


totalBirths_ed <- input_totalBirths %>%
  mutate(Source_factor = as.factor(type)) %>%
  mutate(date = dmy(year_ending_date)) %>%
  mutate(births = as.numeric(annual_births)) %>%
  data.frame()

Fig4 <- totalBirths_ed %>%
  ggplot(aes(x=date, y=births, color=Source_factor, group=Source_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_x_date(labels = date_format("%Y"))+
  scale_y_continuous(limits=c(100, 140), breaks=c(100, 110, 120, 130, 140), labels = c('100K', '110K', '120K', '130K', '140K'))
# labs(title = "Annual births in London 2001 to 2023",
  #     caption = paste0("Sources: As for chart in previous report"))
Fig4

ggsave (filename = (paste0(chart_dir, "Births.png")),
         plot = Fig4,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")

```

```{r fig5, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal2 <- c("#eb861e", "#5ea15d")

Births_MothersUKnonUK_ed <- input_Births_MothersUKnonUK %>%
  mutate(COB_factor = as.factor(mcob)) %>%
  mutate(PopulationK = value/1000) %>%
  data.frame()

Fig5 <- Births_MothersUKnonUK_ed %>%
   mutate(label = if_else(year == max(year), as.character(COB_factor),NA_character_)) %>% 
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
   scale_color_manual(values=my_pal2, guide = FALSE)  +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  geom_label_repel(aes(label = label), nudge_x = 0.2)+
  scale_x_continuous(limits = c (2001, 2023), breaks = c(2001, 2004, 2007, 2010, 2013, 2016, 2019, 2022)) + 
  scale_y_continuous(limits=c(40, 80), breaks=c(40, 50, 60, 70, 80), labels = c('40', '50', '60', '70', '80'))
 # labs(title = "Annual births in London 2001 to 2021 by whether mother was born in UK",
   #    caption = paste0("Sources: As for chart in previous report"))
Fig5

ggsave (filename = (paste0(chart_dir, "Births_COBMothers_UKnonUK.png")),
         plot = Fig5,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")

```

```{r fig5_B, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# chart for report

Fig5_rep <- Births_MothersUKnonUK_ed %>%
   mutate(label = if_else(year == max(year), as.character(COB_factor),NA_character_)) %>% 
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
   scale_color_manual(values=my_pal2, guide = FALSE)  +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  geom_label_repel(aes(label = label), nudge_x = 0.2)+
  scale_x_continuous(limits = c (2001, 2023), breaks = c(2001, 2004, 2007, 2010, 2013, 2016, 2019, 2022)) + 
  scale_y_continuous(limits=c(40, 80), breaks=c(40, 50, 60, 70, 80), labels = c('40', '50', '60', '70', '80'))
 # labs(title = "Annual births in London 2001 to 2021 by whether mother was born in UK",
   #    caption = paste0("Sources: As for chart in previous report"))
Fig5

ggsave (filename = "C:/Families/Charts_for_Daryl/21_L_Births_COBMothers_UKnonUK.svg",
         plot = Fig5_rep,
         device = "svg",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")

```

```{r fig6, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

Births_MothersRegion_ed <- input_Births_MothersRegion  %>%
  mutate(COB_factor = as.factor(mcob)) %>%
  mutate(PopulationK = value/1000) %>%
  data.frame()

my_pal3 <- c("#6da7de", "#d82222", "#943fa6", "#63c5b5", "#eb861e")

Fig6 <- Births_MothersRegion_ed %>%
    mutate(label = if_else(year == max(year), as.character(COB_factor),NA_character_)) %>% 
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
    geom_label_repel(aes(label = label), nudge_x = 0.2)+
   scale_color_manual(values=my_pal3, guide = FALSE)  +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
    scale_x_continuous(limits = c (2001, 2024), breaks = c(2001, 2004, 2007, 2010, 2013, 2016, 2019, 2022)) + 
  scale_y_continuous(limits=c(0, 30), breaks=c(0, 10, 20, 30), labels = c('0', '10', '20', '30'))
#  labs(title = "Annual births in London 2001-2022 by mother's region of birth (Non UK)",
#       caption = paste0("Sources: As for chart in previous report"))
Fig6

ggsave (filename = (paste0(chart_dir, "Births_COBMothers_Region.png")),
         plot = Fig6,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")


```


```{r fig6_B, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Chart for report


Fig6_rep <- Births_MothersRegion_ed %>%
    mutate(label = if_else(year == max(year), as.character(COB_factor),NA_character_)) %>% 
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
    geom_label_repel(aes(label = label), nudge_x = 0.2)+
   scale_color_manual(values=my_pal3, guide = FALSE)  +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
    scale_x_continuous(limits = c (2001, 2024), breaks = c(2001, 2004, 2007, 2010, 2013, 2016, 2019, 2022)) + 
  scale_y_continuous(limits=c(0, 30), breaks=c(0, 10, 20, 30), labels = c('0', '10', '20', '30'))
#  labs(title = "Annual births in London 2001-2022 by mother's region of birth (Non UK)",
#       caption = paste0("Sources: As for chart in previous report"))
Fig6_rep

ggsave (filename = "C:/Families/Charts_for_Daryl/21_M_Births_COBMothers_Region.svg",
         plot = Fig6_rep,
         device = "svg",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")


```
