---
title: "Population, Nov 23rd and Dec 7th 2023"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(bslib)
library(DT)
library(dplyr)
library(gglaplot)
library(ggplot2)
library(data.table)
library(tidyr)
library(stringr)
library(tidyverse)
library(plotly)
library(sf)
library(htmlwidgets)
library(knitr)
library(lubridate)
library(maps)
library(scales)
library(forcats)

data_dir <- 'DATA/'
chart_dir <- 'CHARTS/'

#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}


## Import census population data

input_2011data <- fread(paste0(data_dir,"Census2011_CompiledSouthern_SYA_byBorough.csv"))%>% 
  data.frame()

# convert 2011 data from wide to long format

input_2011data_long <- input_2011data %>% 
  pivot_longer(
    cols = `All`:`X100`, 
    names_to = "year",
    values_to = "Value2011") %>%
  mutate(Age_code = as.numeric(gsub("X", "", year))) %>%
  mutate(census = 2011) %>%
  select (-c(year)) %>%
    data.frame()

# Input file that will enable filling in missing values due to district changes

input_district_changes_clean <- read_rds("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/district_changes_clean.rds") %>%
  data.frame()

#  Match "LA_code" in 2011 file to the "CHANGED FROM" code in district changes file
# and add the variables corresponding to the "CHANGED TO" code in the district changes file 

# This is because some LAs in 2021 were formed from merging groups of LAs in 2011 

input_2011data_corrected <- input_2011data_long %>% 
  left_join(input_district_changes_clean, by=c("LA_code" = "changed_from_code")) %>%
  mutate(new_code = ifelse(is.na(changed_to_code),  LA_code, changed_to_code)) %>%
  mutate(new_name = ifelse(is.na(changed_to_code), LA_name, changed_to_name)) %>%
    data.frame() 

# When merging, if there is more than one old LA, I will sum the values 

input_2011data_corrected_final <- input_2011data_corrected %>% 
     # drop the variables we don't need
  select(-c(changed_to_name, changed_to_code, changed_from_name, year, desc, entity_type, split, merge)) %>%
  group_by(new_code, Age_code, new_name, Region_name, Region_code) %>%   
     #Now calculate total 
  summarise(Sumvalue2011  = sum(Value2011)) %>%  
  data.frame() 

# Input 2021 census data

input_2021data_long <- fread(paste0(data_dir,"Census2021_NumbersPopulationByYearofAge_byLA_long.csv"))%>% 
  mutate(census = 2021) %>%
  select (-c(Age_desc)) %>%
  mutate(Value2021 = Value) %>%
  data.frame()

# Merge the two datasets

Southern_pop <- input_2021data_long %>%
  left_join(input_2011data_corrected_final, by=c("LA_code"="new_code", "Age_code"="Age_code", "LA_name" = "new_name"))%>% 
  data.frame() 

#--------------------------------------------
# Group to get LA totals for each of the two time points

Census_total_byLA <- Southern_pop %>% 
  drop_na() %>%
  group_by(LA_code, LA_name, Region_code, Region_name) %>% 
  summarise(Sum_value2011 = sum(Sumvalue2011), Sum_value2021 = sum(Value2021)) %>%
  data.frame()

# Group again to get census total for Regions for the two time points

Census_total_byRegion <- Census_total_byLA %>% 
  group_by(Region_code, Region_name) %>% 
  summarise(Total_value2011 = sum(Sum_value2011), Total_value2021 = sum(Sum_value2021)) %>%
  data.frame()
# For London 2011 = 8173941; 2021 = 879975

```


```{r setup3, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

## Compare 0 year olds in 2011 with 10 year olds in 2021

input_2011data_corrected_age_zero <- input_2011data_corrected_final %>% 
  filter(Age_code == 0) %>%    
  data.frame() 

# Input 2021 census data and select for age 10

input_2021data_age_10_long <- input_2021data_long %>%
   filter(Age_code == 10) %>%  
  data.frame()

# Merge the two datasets

Southern_pop_comp <- input_2011data_corrected_age_zero  %>%
  left_join(input_2021data_age_10_long, by=c("new_code"="LA_code", "new_name" = "LA_name"))%>% 
  data.frame() 
 
# Calculate change

South_ageZeroandTen_calc <- Southern_pop_comp %>%
  mutate(changePerc = ((Value2021 - Sumvalue2011)*100/Sumvalue2011)) %>%
    drop_na() %>%
  data.frame()

#quantile(South_ageZeroandTen_calc$changePerc)
#quantile(South_ageZeroandTen_calc$changePerc, probs = seq(0, 1, 1/5))


```



```{r fig_pop_change_cohort_1, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Interactive map of change 

# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)

londonmap6_diverge = c('#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf')
londonmap5 = c("#f46d43", "#fdae61", "#fee090", "#ffffbf", "#e0f3f8")

# Match boundary data with pop data and create categories for mapping

change_South_geog <- South_ageZeroandTen_calc %>% 
  left_join(borough_boundaries, by=c("new_code"="LAD21CD")) %>%
  mutate(Perc_Cat = cut(changePerc, breaks = c(-40, -28, -16, -5, 5, 24, 40),
                             right=FALSE,
                             labels = c(" -40.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 40.00"))) %>%
  data.frame()

cohort_change_map <- change_South_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N,
                 text = paste("LA name: ",  new_name,
                              "<br>Percent change: ",
                              formatC(changePerc, format="f", big.mark=",", digits=2))),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2011 and 2021 (zeros to ten year olds) in London", 
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")
cohort_change_map

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")


# Interactive map using ggplotly
cohort_change_map_int <- ggplotly(cohort_change_map, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Cohort change between 2011 and 2021 (zeros to ten year olds) in London<b>", 
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='SMA',
                                font = list(family = "Arial", size = 14)),  
                     font = list(family = "Arial", size = 14))) %>%  
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography", 
                            showarrow = F, xref='paper', yref='paper', 
                            font=list(size=14, family = "Arial")), 
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4)) 
cohort_change_map_int

```

```{r fig_UK_map1, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# 
# # Import NUTS3 boundaries for UK
# boundaries <-
#   st_read("C:/Geographical/NUTS3_boundaries/NUTS_Level_3_(January_2018)_Boundaries.shp", quiet = TRUE)
# 
# UK <- boundaries %>%
#   ggplot()+
#   geom_point(aes(x=long, y=lat)) +
#   geom_sf(aes(geometry=geometry),lwd = 0.2, colour = "black")
# UK

```


```{r fig_UK_map2, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# 
# # Import NUTS2 boundaries for UK
# boundaries <-
#   st_read("C:/Geographical/NUTS2_boundaries/NUTS_Level_2_(January_2018)_Boundaries.shp", quiet = TRUE)
# 
# UK <- boundaries %>%
#   ggplot()+
#   geom_point(aes(x=long, y=lat)) +
#   geom_sf(aes(geometry=geometry),lwd = 0.2, colour = "black")
# UK

```


```{r fig_pop_change_cohort_2, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Now doing map just for area around London
# Experiment with colours

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

## Interactive map of change with London border

# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)

# code from file 
# C:/Computing_and_Analysis_Resources/Vignettes_(includes%20GLA)/GGLA/v01_Using_GLA_colour_palettes.html

londonmap7_diverge = gla_pal(gla_theme = "default", palette_type = "diverging",
        main_colours = c("purple", "turquoise"), n = 7, inc0 = TRUE)


#londonmap6_diverge = c('#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf')
#londonmap5 = c("#f46d43", "#fdae61", "#fee090", "#ffffbf", "#e0f3f8")

# Match boundary data with pop data and create categories for mapping

change_South_geog <- South_ageZeroandTen_calc %>% 
  left_join(borough_boundaries, by=c("new_code"="LAD21CD")) %>%
  mutate(Perc_Cat = cut(changePerc, breaks = c(-40, -28, -16, -5, 5, 16, 28, 40),
                             right=FALSE,
                             labels = c(" -40.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 15.99",
                                        " 16.0  - 27.99",
                                        " 28.0  - 40.00"))) %>%
  data.frame()

cohort_change_map_expanded <- change_South_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N,
                 text = paste("LA name: ",  new_name,
                              "<br>Percent change: ",
                              formatC(changePerc, format="f", big.mark=",", digits=2))),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge) + 
#  scale_alpha_manual(values=c(0.5, 0)) +
  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  #annotate(geom = "rect", ymax = 210000, ymin = 140000, xmax = 570000, xmin = 490000, colour = "black", fill = NA) +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))


ggsave (filename = (paste0(chart_dir, "cohort_change_map_expanded.png")),
         plot = cohort_change_map_expanded,
         device = "png",
         dpi=600,
         width = 9,
         height = 5.56,
         units = "in")


cohort_change_map_expanded

# Interactive map using ggplotly

cohort_change_map_expanded_int <- ggplotly(cohort_change_map_expanded, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)<b>",
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='% change',
                                font = list(family = "Arial", size = 14)),
                     font = list(family = "Arial", size = 14))) %>%
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
                            showarrow = F, xref='paper', yref='paper',
                            font=list(size=14, family = "Arial")),
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))
cohort_change_map_expanded_int

```


```{r fig_pop_change_cohort_3, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Doing map just for area around London experimenting with colours

londonmap7_diverge2 = c('#943fa6', '#b47bbe', '#d2b4d6', '#eeeeee', '#c3e1db', '#96d3c8', '#63c5b5')

# Match boundary data with pop data and create categories for mapping

cohort_change_map_expanded2 <- change_South_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N,
                 text = paste("LA name: ",  new_name,
                              "<br>Percent change: ",
                              formatC(changePerc, format="f", big.mark=",", digits=2))),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge2) + 
#  scale_alpha_manual(values=c(0.5, 0)) +
  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  #annotate(geom = "rect", ymax = 210000, ymin = 140000, xmax = 570000, xmin = 490000, colour = "black", fill = NA) +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

cohort_change_map_expanded2

# Interactive map using ggplotly

cohort_change_map_expanded_int2 <- ggplotly(cohort_change_map_expanded2, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)<b>",
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='% change',
                                font = list(family = "Arial", size = 14)),
                     font = list(family = "Arial", size = 14))) %>%
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
                            showarrow = F, xref='paper', yref='paper',
                            font=list(size=14, family = "Arial")),
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))
cohort_change_map_expanded_int2

```

```{r setup4, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

### New analysis on December 7th using MYE data

## Import population data

input_2011and2021data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2011and2021only.csv"))%>% 
  data.frame()

input_2001and2011data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2001and2011only.csv"))%>% 
  data.frame()

input_region_lookup_tabledata <- fread(paste0(data_dir,"Local_Authority_District_to_Region_(December_2020)_Lookup_in_England.csv"))%>% 
  data.frame()

# Merge the two datasets

all_pop <- input_2001and2011data %>%
  left_join(input_2011and2021data, by=c("ladcode18"="ladcode21", "age"="age", "sex" = "sex"))%>% 
  data.frame() 

all_pop_region <- all_pop %>%
  left_join(input_region_lookup_tabledata, by=c("ladcode18"="LAD20CD"))%>% 
  data.frame() 


#--------------------------------------------
# Group to get LA totals for each of the three time points

Census_total_byLA <- all_pop_region %>% 
#  drop_na() %>%
  group_by(ladcode18, laname18, RGN20CD, RGN20NM) %>% 
  summarise(Sum2001 = sum(X2001), Sum2011 = sum(X2011.x), Sum2021 = sum(X2021)) %>%
  data.frame()

# Group again to get census total for Regions for the two time points

Census_total_byRegion <- Census_total_byLA %>% 
  group_by(RGN20CD, RGN20NM) %>% 
  summarise(Regtot2001 = sum(Sum2001), Regtot2011 = sum(Sum2011), Regtot2021 = sum(Sum2021)) %>%
  data.frame()

# For London, 2001 = 7322403, 2011 = 8204407 and 2021 = 8804769

#-----------------------------------------------------------------
# Do again but drop region

Census_total_byLA_noregion <- all_pop %>% 
#  drop_na() %>%
  group_by(ladcode18, laname18) %>% 
  summarise(Sum2001 = sum(X2001), Sum2011 = sum(X2011.x), Sum2021 = sum(X2021)) %>%
  data.frame()
#------------------------------------------------------

```


```{r setup5, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

### First do with dataframes including region

## Compare 0 year olds in 2011 with 10 year olds in 2021

Census_byLA_ageZero <- all_pop_region %>% 
  mutate(pop2001zero = X2001) %>%
  mutate(pop2011zero = X2011.x) %>%
  mutate(pop2021zero = X2021) %>%
  filter(age == 0) %>%  
  select(c(ladcode18,laname18, sex, RGN20CD, RGN20NM, pop2001zero, pop2011zero, pop2021zero)) %>%
  data.frame() 

Census_byLA_ageTen <- all_pop_region %>% 
  mutate(pop2001ten = X2001) %>%
  mutate(pop2011ten = X2011.x) %>%
  mutate(pop2021ten = X2021) %>%
  filter(age == 10) %>%  
  select(c(ladcode18,laname18, sex, RGN20CD, RGN20NM, pop2001ten, pop2011ten, pop2021ten)) %>%
  data.frame()

# Merge the two datasets

Census_byLA_agezeroand10 <- Census_byLA_ageZero  %>%
  left_join(Census_byLA_ageTen, by=c("ladcode18"="ladcode18", "laname18"="laname18", "sex" = "sex", "RGN20CD" = "RGN20CD", "RGN20NM" = "RGN20NM")) %>% 
  data.frame() 
 
# Calculate change

Census_byLA_agezeroand10_change <- Census_byLA_agezeroand10 %>% 
  group_by(ladcode18, laname18, RGN20CD, RGN20NM) %>% 
  summarise(Sum2001zero = sum(pop2001zero), 
            Sum2011zero = sum(pop2011zero), 
            Sum2021zero = sum(pop2021zero), 
            Sum2001ten = sum(pop2001ten), 
            Sum2011ten = sum(pop2011ten), 
            Sum2021ten = sum(pop2021ten)) %>%
  mutate(Change_2011to2021 = ((Sum2021ten - Sum2011zero)*100/Sum2011zero)) %>%
  mutate(Change_2001to2011 = ((Sum2011ten - Sum2001zero)*100/Sum2001zero)) %>%
  drop_na() %>%
  data.frame()

quantile(Census_byLA_agezeroand10_change$Change_2011to2021, probs = seq(0, 1, 1/5))
quantile(Census_byLA_agezeroand10_change$Change_2001to2011, probs = seq(0, 1, 1/5))


```


```{r setup6,include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

# Do again but drop region in case it's that which is causing the problem

## Compare 0 year olds in 2011 with 10 year olds in 2021

Census_byLA_ageZero_noregion <- all_pop %>% 
  mutate(pop2001zero = X2001) %>%
  mutate(pop2011zero = X2011.x) %>%
  mutate(pop2021zero = X2021) %>%
  filter(age == 0) %>%  
  select(c(ladcode18,laname18, sex, pop2001zero, pop2011zero, pop2021zero)) %>%
  data.frame() 

Census_byLA_ageTen_noregion <- all_pop %>% 
  mutate(pop2001ten = X2001) %>%
  mutate(pop2011ten = X2011.x) %>%
  mutate(pop2021ten = X2021) %>%
  filter(age == 10) %>%  
  select(c(ladcode18,laname18, sex, pop2001ten, pop2011ten, pop2021ten)) %>%
  data.frame()

# Merge the two datasets

Census_byLA_agezeroand10_noregion <- Census_byLA_ageZero_noregion  %>%
  left_join(Census_byLA_ageTen_noregion, by=c("ladcode18"="ladcode18", "laname18"="laname18", "sex" = "sex")) %>% 
  data.frame() 
 
# Calculate change

Census_byLA_agezeroand10_change_noregion <- Census_byLA_agezeroand10_noregion %>% 
  group_by(ladcode18, laname18) %>% 
  summarise(Sum2001zero = sum(pop2001zero), 
            Sum2011zero = sum(pop2011zero), 
            Sum2021zero = sum(pop2021zero), 
            Sum2001ten = sum(pop2001ten), 
            Sum2011ten = sum(pop2011ten), 
            Sum2021ten = sum(pop2021ten)) %>%
  mutate(Change_2011to2021 = ((Sum2021ten - Sum2011zero)*100/Sum2011zero)) %>%
  mutate(Change_2001to2011 = ((Sum2011ten - Sum2001zero)*100/Sum2001zero)) %>%
  drop_na() %>%
  data.frame()

#quantile(Census_byLA_agezeroand10_change_noregion$Change_2011to2021, probs = seq(0, 1, 1/5))
#quantile(Census_byLA_agezeroand10_change_noregion$Change_2001to2011, probs = seq(0, 1, 1/5))


```


```{r fig_pop_change_cohort_4, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Interactive map of cohort change from 2011 to 2021 

# # Import LA boundaries for England and Wales - trying with Yiran's data
# borough_boundaries <-
#   st_read("C:/Families/London_families_Housing/DATA/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)

# Import LA boundaries for England and Wales - trying with 2015 data
borough_boundaries <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2015)_Boundaries.shp", quiet = TRUE)

# Match boundary data with pop data and create categories for mapping

change_2011to2021_geog <- Census_byLA_agezeroand10_change_noregion %>% 
  left_join(borough_boundaries, by=c("ladcode18"="lad15cd")) %>%
  mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2011to2021_map <- change_2011to2021_geog %>%
  ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2011 and 2021 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")
change_2011to2021_map

# # Interactive map using ggplotly
# change_2011to2021_map_int <- ggplotly(change_2011to2021_map, tooltip = "text") %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>Cohort change between 2011 and 2021 (zeros to ten year olds) in London (using MYE)<b>", 
#                      font=list(size = 15, family = "Arial")),
#          font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
#          legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
#                      title=list(text='Percentage change',
#                                 font = list(family = "Arial", size = 14)),  
#                      font = list(family = "Arial", size = 14))) %>%  
#   # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
#   layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography", 
#                             showarrow = F, xref='paper', yref='paper', 
#                             font=list(size=14, family = "Arial")), 
#          margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4)) 
# change_2011to2021_map_int

```



```{r fig_pop_change_cohort_5, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Interactive map of cohort change from 2001 to 2011 


# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)

# Match boundary data with pop data and create categories for mapping

change_2001to2011_geog  <- Census_byLA_agezeroand10_change %>% 
  left_join(borough_boundaries, by=c("ladcode18"="LAD21CD")) %>%
  mutate(Perc_Cat = cut(Change_2001to2011, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2001to2011_map <- change_2001to2011_geog %>%
  ggplot()+
  geom_point(aes(x=BNG_E, y=BNG_N,
                 text = paste("LA name: ",  laname18,
                              "<br>Percent change: ",
                              formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
             alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2011 and 2021 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")

# Interactive map using ggplotly
change_2001to2011_map_int <- ggplotly(change_2001to2011_map, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Cohort change between 2011 and 2021 (zeros to ten year olds) in London (using MYE)<b>", 
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='Percentage change',
                                font = list(family = "Arial", size = 14)),  
                     font = list(family = "Arial", size = 14))) %>%  
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography", 
                            showarrow = F, xref='paper', yref='paper', 
                            font=list(size=14, family = "Arial")), 
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4)) 
change_2001to2011_map_int

```

```{r fig_pop_change_cohort_6, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Now doing map just for area around London

londonmap7_diverge2 = c('#943fa6', '#b47bbe', '#d2b4d6', '#eeeeee', '#c3e1db', '#96d3c8', '#63c5b5')

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

change_2011to2021_map_london <- change_2011to2021_geog %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
 
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
   scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2011to2021_map_london

# Interactive map using ggplotly
# 
# change_2011to2021_map_london_int <- ggplotly(change_2011to2021_map_london, tooltip = "text") %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021) using MYE<b>",
#                      font=list(size = 15, family = "Arial")),
#          font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
#          legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
#                      title=list(text='% change',
#                                 font = list(family = "Arial", size = 14)),
#                      font = list(family = "Arial", size = 14))) %>%
#   # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
#   layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
#                             showarrow = F, xref='paper', yref='paper',
#                             font=list(size=14, family = "Arial")),
#          margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))
# change_2011to2021_map_london_int

```

```{r fig_pop_change_cohort_7, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Now doing map just for area around London for earlier change

londonmap7_diverge2 = c('#943fa6', '#b47bbe', '#d2b4d6', '#eeeeee', '#c3e1db', '#96d3c8', '#63c5b5')

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

change_2001to2011_map_london <- change_2001to2011_geog %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
   scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2001 to 10 y.o. in 2011)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2001to2011_map_london

# Interactive map using ggplotly

# change_2001to2011_map_london_int <- ggplotly(change_2001to2011_map_london, tooltip = "text") %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>Inter-census cohort change (<1 y.o in 2001 to 10 y.o. in 2011) using MYE<b>",
#                      font=list(size = 15, family = "Arial")),
#          font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
#          legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
#                      title=list(text='% change',
#                                 font = list(family = "Arial", size = 14)),
#                      font = list(family = "Arial", size = 14))) %>%
#   # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
#   layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
#                             showarrow = F, xref='paper', yref='paper',
#                             font=list(size=14, family = "Arial")),
#          margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))
# change_2001to2011_map_london_int

```


```{r setup7, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

### Analysis on December 7th using MYE data, starting again without merging files

## Import population data

input_2011and2021data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2011and2021only.csv"))%>% 
  data.frame()

input_2001and2011data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2001and2011only.csv"))%>% 
  data.frame()

input_region_lookup_tabledata <- fread(paste0(data_dir,"Local_Authority_District_to_Region_(December_2020)_Lookup_in_England.csv"))%>% 
  data.frame()

```


```{r setup8, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

#-----------------------------------------------------------------------
## Compare 0 year olds in 2011 with 10 year olds in 2021

LA_2001zero <- input_2001and2011data %>% 
  mutate(pop2001zero = X2001) %>%
  filter(age == 0) %>%  
  data.frame() 

LA_2011ten <- input_2001and2011data %>% 
  mutate(pop2011ten = X2011) %>%
  filter(age == 10) %>%  
  data.frame()

# Merge the two datasets

LA_2001and2011 <- LA_2001zero  %>%
  left_join(LA_2011ten, by=c("ladcode18"="ladcode18", "laname18"="laname18", "sex" = "sex")) %>% 
  data.frame() 

# calculate change
LA_2001and2011_agezeroand10_change <- LA_2001and2011 %>% 
  group_by(ladcode18, laname18) %>% 
  summarise(Sum2011ten = sum(pop2011ten), 
            Sum2001zero = sum(pop2001zero)) %>%
  mutate(Change_2001to2011 = ((Sum2011ten - Sum2001zero)*100/Sum2001zero)) %>%
  drop_na() %>%
  data.frame()

#--------------------------------------------------------------------------------

## Compare 0 year olds in 2011 with 10 year olds in 2021

LA_2011zero <- input_2011and2021data %>% 
  mutate(pop2011zero = X2011) %>%
  filter(age == 0) %>%  
  data.frame() 

LA_2021ten <- input_2011and2021data %>% 
  mutate(pop2021ten = X2021) %>%
  filter(age == 10) %>%  
  data.frame()

# Merge the two datasets

LA_2011and2021 <- LA_2011zero  %>%
  left_join(LA_2021ten, by=c("ladcode21"="ladcode21", "laname21"="laname21", "sex" = "sex")) %>% 
  data.frame() 

# calculate change
LA_2011and2021_agezeroand10_change <- LA_2011and2021 %>% 
  group_by(ladcode21, laname21) %>% 
  summarise(Sum2021ten = sum(pop2021ten), 
            Sum2011zero = sum(pop2011zero)) %>%
  mutate(Change_2011to2021 = ((Sum2021ten - Sum2011zero)*100/Sum2011zero)) %>%
  drop_na() %>%
  data.frame()

#----------------------------

#quantile(LA_2001and2011_agezeroand10_change$Change_2001to2011, probs = seq(0, 1, 1/5))
#quantile(LA_2011and2021_agezeroand10_change$Change_2011to2021, probs = seq(0, 1, 1/5))

```


```{r fig_pop_change_cohort_8, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Trying again with map
## Interactive map of cohort change from 2011 to 2021 


# # Import LA boundaries for England and Wales - trying with Yiran's data
# borough_boundaries <-
#   st_read("C:/Families/London_families_Housing/DATA/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)

# Import LA boundaries for England and Wales - trying with 2015 data
borough_boundaries <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2020)_UK_BGC.shp", quiet = TRUE)


# Match boundary data with pop data and create categories for mapping

change_2011to2021_geog <- LA_2011and2021_agezeroand10_change %>% 
  left_join(borough_boundaries, by=c("ladcode21"="LAD20CD")) %>%
  mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2011to2021_map <- change_2011to2021_geog %>%
  ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ", laname21,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2011 and 2021 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")
change_2011to2021_map

# # Interactive map using ggplotly
# change_2011to2021_map_int <- ggplotly(change_2011to2021_map, tooltip = "text") %>%
#   layout(title= list(x = 0.05,
#                      text = "<b>Cohort change between 2011 and 2021 (zeros to ten year olds) in London (using MYE)<b>",
#                      font=list(size = 15, family = "Arial")),
#          font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
#          legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
#                      title=list(text='Percentage change',
#                                 font = list(family = "Arial", size = 14)),
#                      font = list(family = "Arial", size = 14))) %>%
#   # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
#   layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
#                             showarrow = F, xref='paper', yref='paper',
#                             font=list(size=14, family = "Arial")),
#          margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))
# 
# change_2011to2021_map_int

```


```{r fig_pop_change_cohort_9, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Trying again with map
## Interactive map of cohort change from 2001 to 2011 

# # Import LA boundaries for England and Wales - trying with Yiran's data
# borough_boundaries <-
#   st_read("C:/Families/London_families_Housing/DATA/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)

# Import LA boundaries for England and Wales - trying with 2015 data
borough_boundaries <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2015)_Boundaries.shp", quiet = TRUE)


# Match boundary data with pop data and create categories for mapping

change_2001to2011_geog <- LA_2001and2011_agezeroand10_change %>% 
  left_join(borough_boundaries, by=c("ladcode18"="lad15cd")) %>%
  mutate(Perc_Cat = cut(Change_2001to2011, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2001to2011_map <- change_2001to2011_geog %>%
  ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ", laname21,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2001 and 2011 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")
change_2001to2011_map

# Interactive map using ggplotly
change_2001to2011_map_int <- ggplotly(change_2001to2011_map, tooltip = "text") %>%
  layout(title= list(x = 0.05,
                     text = "<b>Cohort change between 2001 and 2011 (zeros to ten year olds) in London (using MYE)<b>",
                     font=list(size = 15, family = "Arial")),
         font=list(size = 14, family = "Arial", color = "black", fontface = "bold"),
         legend=list(orientation = "v", xanchor = "center", x = 1.1, y = 0.3,
                     title=list(text='Percentage change',
                                font = list(family = "Arial", size = 14)),
                     font = list(family = "Arial", size = 14))) %>%
  # add_annotations(text="", showarrow=FALSE, legendtitle=TRUE) %>%
  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS; Chart: GLA demography",
                            showarrow = F, xref='paper', yref='paper',
                            font=list(size=14, family = "Arial")),
         margin = list(l = 0,r = 0,  b =40,  t = 70,  pad = 4))

change_2001to2011_map_int

```

```{r fig_pop_change_cohort_10, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Now doing map just for area around London for 2011 to 2021

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

londonmap7_diverge2 = c('#943fa6', '#b47bbe', '#d2b4d6', '#eeeeee', '#c3e1db', '#96d3c8', '#63c5b5')

# Match boundary data with pop data and create categories for mapping

change_2011to2021_map_london <- change_2011to2021_geog %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
   scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2011to2021_map_london


```

```{r fig_pop_change_cohort_11, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Now doing map just for area around London for earlier change

londonmap7_diverge2 = c('#943fa6', '#b47bbe', '#d2b4d6', '#eeeeee', '#c3e1db', '#96d3c8', '#63c5b5')

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

# Match boundary data with pop data and create categories for mapping

change_2001to2011_map_london <- change_2001to2011_geog %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
   scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2001 to 10 y.o. in 2011)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2001to2011_map_london

```